name: Build Samples

# This Workflow Will Be Triggered Automatically

on: [push, pull_request]

jobs:

  # Build Simple Swerve
  swerve-simple:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew Executable
      run: chmod +x ./samples/swerve-simple/gradlew
    - name: Execute Build
      run: ./samples/swerve-simple/gradlew build

  # Build Swerve
  swerve-auton:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew Executable
      run: chmod +x ./samples/swerve-auton/gradlew
    - name: Execute Build
      run: ./samples/swerve-auton/gradlew build

  # Build Simple Differential
  differential-simple:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew Executable
      run: chmod +x ./samples/differential-simple/gradlew
    - name: Execute Build
      run: ./samples/differential-simple/gradlew build

  # Build Differential
  differential-auton:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew Executable
      run: chmod +x ./samples/differential-auton/gradlew
    - name: Execute Build
      run: ./samples/differential-auton/gradlew build
